
server:
  port: 2100
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: order
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 1
        min-idle: 1
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

#feign.client.config.feignName.connectTimeout: 20000
#feign.client.config.feignName.readTimeout: 20000




#eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: false
  client:
    default-config: default
      connectionTimeout:20000
      readTimeout:20000
  httpclient:
    connection-timeout: 200000
    connection-timer-repeat: 200000


#请求处理的超时时间
ribbon.ReadTimeout: 120000
#请求连接的超时时间
ribbon.ConnectTimeout: 30000



#hystrix:
#  command:
#      default:
#        execution:
#          isolation:
#            thread:
#              timeoutInMilliseconds: 50000
#  metrics:
#    polling-interval-ms: 50000

hystrix.command.default.execution.timeout.enabled: false



#eureka:
#  instance:
#    hostname: order_client


#feign:
#    client:config:
#        feignName:
#            connectTimeout: 50000
#            readTimeout: 50000


